### PR TITLE
Checkbox indeterminate

### PR DESCRIPTION
**Pull request by happylinks**
Allows you to use checkboxes with status "indeterminate". The value will be "null".
You can make Tri-state checkboxes this way.

http://css-tricks.com/indeterminate-checkboxes/

### CODE REVIEW

**Comment by rhubarbselleven** [comment]
Hi @happylinks. Thanks for the PR!

Can you expand on what you're thoughts are around what would happen to the model? Eg: If a value is set to null although it can represent a state, a value of null means something else in a restful model. 

I'm feeling that the `indeterminate` attribute is more of a visual thing:

http://www.w3.org/TR/html5/forms.html#dom-input-indeterminate

**Comment by happylinks** [comment]
I'm using this for filters, so I get the filter-form using Syphon and this way I can see if a filter is:
- not touched -> null
- on -> true
- off -> false

So I don't really use it for a model, but for parameters in the url.

**Comment by rhubarbselleven** [comment]
Thanks @happylinks for the good work so far.

Are you able to back this with some tests? 

You'll also want to rebase off the minor branch and please exclude your 7224a569c5df8401e3d40ecfee7b1f1e9079bc7e commit

**Comment by rhubarbselleven** [comment]
Hey @happylinks I've recreated this in #95. Thanks for the work so far

**Comment by happylinks** [comment]
@rhubarbselleven Ah thanks, was pretty busy the last couple of weeks so didn't have the time. Thanks for fixing it for me, hope it'll get merged!

**Comment by rhubarbselleven** [comment]
Np, thanks for doing the legwork ;)

I'm planing on a release next week sometime. Once others in the team have had a review, then it should be on that boat

**Comment by rhubarbselleven** [comment]
Hi @happylinks, not sure if you're watching the other PR. See https://github.com/marionettejs/backbone.syphon/pull/95#issuecomment-82309890

**Pull request closed without merging**
