### PR TITLE
Release/0.5.1

### PR DESCRIPTION
**Pull request by rhubarbselleven**
General housekeeping release to get the repo back in shape for the next iterations

### CODE REVIEW

**Comment by rhubarbselleven** [comment]
Ping @samccone @thejameskyle

**Comment by samccone** [comment]
:+1: will go in tonight unless @thejameskyle has objections

**Comment by thejameskyle** [comment]
:+1:

**Comment by samccone** [comment]
ok merged into master

@thejameskyle can you add me on npm for this project :dancer:

**Comment by rhubarbselleven** [comment]
:+1: thanks guys :balloon:

**Comment by samccone** [comment]
yeah just waiting on npm permissions from @thejameskyle

**Comment by thejameskyle** [comment]
@samccone Added you

**Comment by samccone** [comment]
:heart_eyes:

**Pull request merged**
