### PR TITLE
Upgrade development dependencies to make compatible with node >= 4

### PR DESCRIPTION
**Pull request by blikblum**
I was getting issues running tests.

Only after upgrading mocha and jsdom the npm test ran fine

Unfortunately coverage is not working in any setup

### CODE REVIEW

**Comment by blikblum** [comment]
After a close look, the coverage task is not configured at all.

BTW: Travis fails due to old node version

**Comment by blikblum** [comment]
In #135 i tried to upgrade Travis node version to v6 but build fail in an dependency of old jsdom

Tried here to update to v6 but fails in jshint

Last try with v4 worked fine.

**Comment by blikblum** [comment]
Updated grunt-jshint. 
This combination of versions, works both with node v4 and v6

**Comment by scott-w** [comment]
See #133

**Comment by scott-w** [comment]
I'm closing this from #133

**Pull request closed without merging**
