### PR TITLE
Use `$.find`, not `$.children`, to search for inputs within a specific form

### PR DESCRIPTION
**Pull request by david-davidson**
Fixes https://github.com/marionettejs/backbone.syphon/issues/104

This updates `getForm` to rely on `$.find`, not `$.children`, when searching for inputs within a specific form (not a view). That's consistent with how it handles inputs within a view (`View.$`, which is the equivalent of `$.find`), and it lets Syphon pull data from inputs nested more than one level down, like `<div><input></input></div>`.

/cc @rhubarbselleven 

Marionette: 2.4.1 / Syphon: 0.6.0

### CODE REVIEW

**Comment by samccone** [comment]
:+1: good fix @david-davidson mind squashing this into a single commit

**Comment by david-davidson** [comment]
@samccone Done!

**Comment by samccone** [comment]
:rocket:

**Comment by rhubarbselleven** [comment]
Thanks for this @david-davidson 

One last thing, can you reopen this PR against minor?

**Comment by david-davidson** [comment]
@rhubarbselleven Will do!

**Pull request closed without merging**
