### PR TITLE
Ignore disabled fields

### PR DESCRIPTION
**Pull request by wmadden**

### CODE REVIEW

**Comment by wmadden** [comment]
@samccone yes.

**Comment by wmadden** [comment]
@samccone https://github.com/marionettejs/backbone.syphon/pull/70#issuecomment-76084056

**Comment by samccone** [comment]
I should have been more clear, it is a good choice to do it in this code path.
Given where this logic lives It seems like this would be a hard thing to disable if someone wanted to for whatever reason.

What do you think @wmadden

**Comment by wmadden** [comment]
Good point @samccone. I'd still opt to ignore disabled elements by default since that's the behaviour implemented by browsers. I think if someone wants to specifically include their disabled elements they can do so by a) not disabling them (greying them out in CSS for example) or b) opening their own pull request.

**Comment by wmadden** [comment]
@samccone I rewrote it using @rhubarbselleven's type selection code. This is now easy for people to customize if they want to.

I'm also requesting that you update your `major` branch to this point, since the type selector changes were only available on master.

**Comment by wmadden** [comment]
@samccone any progress here?

**Comment by samccone** [comment]
Lgtm :+1: @rhubarbselleven Want to give it the once over

**Comment by rhubarbselleven** [comment]
:boom: 

Thanks guys.

**Pull request merged**
