### PR TITLE
Updates to key supporting configs

### PR DESCRIPTION
**Pull request by rhubarbselleven**
To be inline with current marionette implementations

### CODE REVIEW

**Comment by rhubarbselleven** [comment]
Waiting on me to double check directories etc

**Comment by samccone** [comment]
yep I think some of the ignores are incorrect per this project

**Comment by rhubarbselleven** [comment]
interestingly the .npmignore on marionette references the old spec directory

**Comment by samccone** [comment]
lol good catch ill fix

**Comment by rhubarbselleven** [comment]
Ok, that should all be good now

**Comment by samccone** [comment]
well done @rhubarbselleven

**Comment by rhubarbselleven** [comment]
ta. releasing my inner librarian

**Pull request merged**
